### ISSUE TITLE
Manual ordering of lists is hardly doable

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#8] opened 2021-09-29 23:09 UTC
Hi Ali!
In Noto v1.5.1, dragging items in order to order a list is quite difficult: I just come from an attempt with 8 fails to shift one note one position upward before I succeeded for the first time, and I chose that technique cause skipping across *multiple* positions has become *totally* uncontrollable (the list comprises 36 notes).

As soon as the element you're moving an  item across starts twitching (or the whole list starts dancing up and down), from that moment you've lost control on where your item lands, it can go to the very top even if you've already dragged it down  across all notes, it can drop to the very bottom although you want it near top, and it can come out anywhere else. 

I've had that problem with articles and labels, and in a quick test it looked like libraries have it, too. 

Manual ordering seems especially hard on lists that can be scrolled several screen heights, BTW.

Android 6.0.1 
(with GMS updated to 21.18.16, cn=M sdk=23)
Webview 93.0.4577.82
Motorola Moto G4
device not rooted

**Comment by SimoneG97** [comment] 2021-09-30 14:54
Hi, reporting in that I have reproduced this weird behavior, looks like it only happens with long lists (tested with 36 notes)

OS: Android 11
Device: Poco F1 (rooted)

**Comment by alialbaali** [comment] 2021-09-30 17:09
@uli-on are you sure it happens with labels and libraries too?

**Comment by alialbaali** [comment] 2021-09-30 17:28
I've uploaded an APK in the release page. Could you please try with that and let me know. [APK](https://github.com/alialbaali/Noto/releases/tag/1.5.2)

**Comment by uli-on** [comment] 2021-09-30 17:47
Thanks, that was *really* fast!
But please don't hold your breath til response comes in, it did not accept
existent libraries/notes.

**Comment by alialbaali** [comment] 2021-09-30 18:12
Are you sure you downloaded the debug version? It should create a new app in your device.

**Comment by uli-on** [comment] 2021-09-30 18:22
You've sent me to v1. 5.2, which installs as v1. 5.1-debug, correct?

Am 30. September 2021 8:12:47 nachm. schrieb Ali Albaali
***@***.***>:

**Comment by alialbaali** [comment] 2021-09-30 18:23
Yes

**Comment by uli-on** [comment] 2021-09-30 18:38
Sorry, the difficulties remain. Sort of, and only trying libraries.

Dragging from the list end say two positions up seems doable, but does not
work flawless yet. I almost always need several attempts. According to my
memories on how it used to be when you introduced manual ordering to Noto,
it's been a piece of cake to reorder a library. (Ordering *notes* wasn't
yet available at that time.)

But if I want to drag a library to the *first* position I must hold it
roughly where the lib counter resides for the rest of the libraries to slip
past it. Only fractions of a second later I lose the lib (although I
continue holding it) and the previous position is restored. Can it be the
"top of counter" position that leads to inadvertedly dropping the lib?

**Comment by alialbaali** [comment] 2021-09-30 21:44
Are you having the same issue you described the first time where the list goes up and down?

**Comment by uli-on** [comment] 2021-09-30 23:10
I'd say yes (even if I've nothing to measure anything with). Feels the same. 

But currently I've no possibility to try on notes, so I must use libraries instead: Setting note sorting to manual is impossible, only alphabetical and date can be chosen.

**Comment by alialbaali** [comment] 2021-10-01 22:39
Can you provide me with screenshots or video of what you're specifically facing?

**Comment by alialbaali** [comment] 2021-10-02 13:35
The file that's responsible for libraries sorting hasn't changed at all since it was added. You can see [here](https://github.com/alialbaali/Noto/blob/master/app/src/main/java/com/noto/app/main/LibraryItemTouchHelperCallback.kt) that the file last time was updated on August 21th, which was the first time I implemented it. 

You're saying libraries sorting was fine at the beginning but now it isn't, I'm finding that hard to believe since I didn't modify the file as I mentioned earlier.

And same goes for notes sorting, see [here](https://github.com/alialbaali/Noto/blob/master/app/src/main/java/com/noto/app/library/NoteItemTouchHelperCallback.kt).

Now there's one problem I can reproduce which is the list goes up and down when ordering manually. This problem can be solved.

If you still have other problems when ordering manually, please provide me with a video so I can better understand where the problem is.

**Comment by SimoneG97** [comment] 2021-10-02 14:05
I tried to reproduce the problem, I think it's not the exact behavious @uli-on described, but it happened mostly on libraries with lists of notes longer that the screen (in the example I use 14 notes).
When trying to change the order of the notes, some of them can't be changed and will snap back to its original position.
Keep in mind I managed to record this behavior with a single note, it happened even with multiple notes resulting in complete mayhem when trying to move a single note.
Here's the video: [https://send.vis.ee/download/1b5666b1a1d251bf/#A6OmpLgw8dSGA7F_1KKOdQ](url)
Didn't know how to share it properly, the link will expire in 7 days or 20 downloads keep in mind

**Comment by alialbaali** [comment] 2021-10-02 14:11
I can reproduce this. The solution for now is to move the item quick without holding it for too long.

I'll see what I can regarding this problem.

**Comment by uli-on** [comment] 2021-10-02 14:16
Thanks both, Andrea and Ali!

**Comment by SimoneG97** [comment] 2021-10-13 21:36
Yep, can confirm the bug is fixed too, might as well close the issue!

**Closed** 2021-10-13 21:41 UTC
Labels: bug
