### ISSUE TITLE
Labels, notes, and folders positions aren't imported correctly.

### ISSUE THREAD

**Issue by uli-on** [alialbaali/Noto#139] opened 2022-09-27 14:25 UTC
Looking at the current export format for labels, there seems no `position` value contained, if I didn't grab something else here from my export file:

```
 "noteLabels": [
        {
            "id": 13,
            "noteId": 117,
            "labelId": 4
        },
```

It'd be cool to have that, too, so reimporting wouldn't derange carefully ordered labels. (I'd gladly try and test what @AI-IMED found in https://github.com/alialbaali/Noto/issues/33#issuecomment-1256938081, otherwise.)

**Comment by alialbaali** [comment] 2022-09-29 13:28
Labels positions are recorded and saved. Look for the key called "labels", it should have every label, name, and its position. 

In the sample you gave, it is basically the relation of notes and labels (using their IDs). As the order (position) of the labels is the same for the folder (that contains them) and the notes (that has them), it's not replicated again. This applies to every label property except the ID.

**Comment by uli-on** [comment] 2022-09-29 13:34
Well, that must have changed recently, more precisely between our longish "label filtering has changed" discourse and now, I had to reorder labels so often those days that it left traces of fright in my mind.

**Comment by alialbaali** [comment] 2022-09-29 13:43
Are you sure about that? Cause, the ordering of labels has been supported since Import/Export.

**Comment by uli-on** [comment] 2022-09-29 13:55
I always wondered about label order after an import, however that may be, it seemed to follow no rules, "creation time", at best, but i keep no records about that.

**Comment by alialbaali** [comment] 2022-09-29 13:59
I see. Should I close this now?

**Comment by uli-on** [comment] 2022-09-29 14:05
Well, it does not work ...

**Comment by alialbaali** [comment] 2022-09-29 14:10
Reproduced.

**Comment by alialbaali** [comment] 2022-09-29 14:27
Re-importing the data, in the next update, should follow the original position.

**Comment by uli-on** [comment] 2022-10-02 21:50
> Re-importing the data, in the next update, should follow the original position.

Did you mean v2.2.0-beta3 already?

**Closed** 2023-01-03 20:06 UTC
Labels: bug
