### ISSUE TITLE
New Note Shortcut doesn't work when app icon is changed

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#100] opened 2022-08-04 18:20 UTC
Steps to reproduce the problem:

- Create a new note shortcut 
- Change the app icon
- Click on the shortcut icon
- Result: "App isn't installed" message.

**Comment by uli-on** [comment] 2022-08-04 19:06
Ah, you've found the trigger! I've had that, too.

**Comment by alialbaali** [comment] 2022-08-05 02:11
This has already been fixed in 2.1.4. Please check it.

**Comment by afmbsr** [comment] 2022-08-05 02:18
I'm using version 2.1.4 already, the problem is still.

**Comment by alialbaali** [comment] 2022-08-05 02:20
Have you tried changing the icon?

**Comment by afmbsr** [comment] 2022-08-05 02:28
The problem is resolved when removing the shortcut and creating a new shortcut, but when changing the application icon, the shortcut does not work again.

**Comment by AI-IMED** [comment] 2022-09-12 06:14
Fixed it, Thanks

**Closed** 2023-01-03 20:06 UTC
Labels: bug
