### ISSUE TITLE
Reverse (orientation, alignment) of the text

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#50] opened 2022-07-11 05:17 UTC
Great application, but it needs more professionalism in dealing with bidirectional texts, please include the feature of manual alignment control as well as correcting the direction of the Arabic text when it begins with a Latin word, the attached image explains everything I said:

![Screenshot_٢٠٢٢٠٧١١_٠٧٥٢٢٧](https://user-images.githubusercontent.com/38974362/178193308-7f3e6b56-c1d4-4f42-a45d-bd3a8f30fa1a.png)

The direction of the text in the notes and words counter also needs to be corrected:

![Screenshot_٢٠٢٢٠٧١١_٠٨٠٦١٣](https://user-images.githubusercontent.com/38974362/178193382-9f322db5-bf40-4621-b4ea-09db6c14bccb.png)

**Comment by alialbaali** [comment] 2022-07-12 14:50
Thanks for reporting these issues.

I managed to fix the issue in the first image by setting the text and layout direction to match the app locale.

As for the second image, it's a [bug](https://github.com/robinhood/ticker/issues/44) in a library I'm using, and I don't think it's going to be fixed anytime soon. The only way to fix it is by disabling the animation when language is Arabic, which is probably what I'm going to do.

**Comment by afmbsr** [comment] 2022-07-12 17:14
> I managed to fix the issue in the first image by setting the text and layout direction to match the app locale.

OK, but you must be sure that the note written in Latin only must not lose its left alignment.

![Screenshot_٢٠٢٢٠٧١٢_١٩٥٤٥٦](https://user-images.githubusercontent.com/38974362/178552531-a4a4713b-6c23-4aac-bdda-24e67e3bd2ce.png)

**Comment by alialbaali** [comment] 2022-07-12 18:06
Of course!

**Comment by afmbsr** [comment] 2022-07-12 18:39
I mean by that, if the application language is Arabic, Regards

**Comment by alialbaali** [comment] 2022-07-12 19:41
Are you asking for a text alignment feature, or are you reporting a bug?

Because currently, there's no issue with the text alignment. Meaning, if you start the text in Arabic, it's going to start from the right regardless if it has English or not after that. And, if you start the text in English, it's going to start from the left regardless if it has Arabic or not after that.

**Comment by afmbsr** [comment] 2022-07-13 06:03
> Are you asking for a text alignment feature, or are you reporting a bug?

both together

> And, if you start the text in English, it's going to start from the left regardless if it has Arabic or not after that.

This is not accurate if the application works with the Arabic interface, yes, some people may need the current situation sometimes, so I suggested that you include the feature of controlling the direction and alignment of the text for more flexibility and greater professionalism.

As for the correct one, it is that the direction of writing is from right to left and alignment to the right as soon as you enter or have at least one Arabic letter in the note

I have an application installed on my phone that deals with the cases that I mentioned, but it is not open source, if you want to take a look at it, I will send you the link to it on the Play Store to your email

**Comment by alialbaali** [comment] 2022-07-13 11:18
![IMAGE 2022-07-13 14:13:58](https://user-images.githubusercontent.com/37933889/178720932-41819d0d-8277-47f0-9672-79d8aa7f9449.jpg)
![IMAGE 2022-07-13 14:14:03](https://user-images.githubusercontent.com/37933889/178720946-7dbf9e4f-3d23-4dab-bc4f-33bcbb916805.jpg)

I attached two images, one with English language being set and the other with Arabic language being set. As you can see, It works exactly how I described it. Are you sure it doesn't work like that for you?

If you're asking for a feature, then that's a different thing, and probably will be supported when Markdown editor becomes available.

**Comment by alialbaali** [comment] 2022-07-17 22:03
The text marked with "X" can be fixed by always aligning the text to the right when the language is Arabic, even if the text is only English. Is that what you want?

**Comment by afmbsr** [comment] 2022-07-18 04:38
It seems that you do not want to add an option to manually control the direction and alignment of text in the application 😔
  Well..if that's the case, you can try the following app and see how it handles text alignment:
  https://github.com/maltaisn/another-notes-app

You can benefit from the following discussion and beyond that you had with the app developer previously to resolve the issue:

  https://github.com/maltaisn/another-notes-app/issues/30#issuecomment-882098165

**Comment by afmbsr** [comment] 2022-07-18 10:46
> For now, I could do it like https://github.com/maltaisn/another-notes-app/issues/30#issuecomment-882119526, if you want.

Sure, I want it.

**Comment by afmbsr** [comment] 2022-07-25 06:51
Thank you very much for the fixes that you have included in version 2.1.3

Regarding the word counter and notes, can you make the correction automatically depend when on the system language Arabic as well?

**Comment by alialbaali** [comment] 2022-07-25 06:54
You're welcome.

Could you please elaborate more about what you're asking?

**Comment by afmbsr** [comment] 2022-07-25 07:22
![Screenshot_٢٠٢٢٠٧٢٥_١٠٠٨٤٦](https://user-images.githubusercontent.com/38974362/180720650-9f4d774f-f512-4a37-83f2-4eb50ab68fa8.png)


Regarding the error shown in the image, it is fixed by simply selecting the Arabic language manually from within the application. I am wondering if you can make this be done automatically depending on the system language when it is Arabic as well.

**Comment by alialbaali** [comment] 2022-07-25 07:57
Understood.

**Comment by afmbsr** [comment] 2022-07-26 15:14
@alialbaali 
I just found out that recent RTL patches are not implemented on the editor window when in landscape mode.

**Comment by afmbsr** [comment] 2022-07-27 07:06
I see that setting the creation date line and getting to italics has cut off part of its edge

![Screenshot_٢٠٢٢٠٧٢٧_١٠٠١٢٦](https://user-images.githubusercontent.com/38974362/181183361-bdf42543-20aa-4050-ba6a-cb95da05a069.jpg)

**Comment by alialbaali** [comment] 2022-07-30 17:19
> @alialbaali I just found out that recent RTL patches are not implemented on the editor window when in landscape mode.

I can't reproduce the issue, could you share a screenshot?

**Comment by alialbaali** [comment] 2022-07-30 17:20
> I see that setting the creation date line and getting to italics has cut off part of its edge
> 
> ![Screenshot_٢٠٢٢٠٧٢٧_١٠٠١٢٦](https://user-images.githubusercontent.com/38974362/181183361-bdf42543-20aa-4050-ba6a-cb95da05a069.jpg)

The solution for this, is to make the font regular instead of italics.

**Comment by afmbsr** [comment] 2022-07-31 04:38
> The solution for this, is to make the font regular instead of italics.

Yes. Or keep the font _italic_, shifting it slightly off the edge

**Comment by afmbsr** [comment] 2022-07-31 13:06
> I can't reproduce the issue, could you share a screenshot?

Of course

![Screenshot_٢٠٢٢٠٧٣١_١٥٥٠٤١](https://user-images.githubusercontent.com/38974362/182027800-8c4c3eb3-a8a3-4acc-bd86-a19aeee005a4.png)

**Comment by alialbaali** [comment] 2022-07-31 18:03
> > I can't reproduce the issue, could you share a screenshot?
> 
> Of course
> 
> ![Screenshot_٢٠٢٢٠٧٣١_١٥٥٠٤١](https://user-images.githubusercontent.com/38974362/182027800-8c4c3eb3-a8a3-4acc-bd86-a19aeee005a4.png)

I don't think that would be possible, since this text editor screen is configured by the system, and not by the app.

**Comment by alialbaali** [comment] 2022-08-01 18:22
Unfortunately, both screens (white and dark) in landscape mode are controlled by the system.

**Comment by afmbsr** [comment] 2022-08-02 08:58
> Unfortunately, both screens (white and dark) in landscape mode are controlled by the system.

So, it is necessary to create an editor screen for the application, because the current editor screen, which is configured by the system, lacks all the elements in the vertical position, such as the note title field, Undo / Redo buttons, etc. .

**Comment by alialbaali** [comment] 2022-08-02 20:42
> > The solution for this, is to make the font regular instead of italics.
> 
> Yes. Or keep the font _italic_, shifting it slightly off the edge

The text is now set to regular instead of italics. I tried to shift it a bit or add spacing but it didn't work.

**Comment by alialbaali** [comment] 2022-08-02 20:45
> > Unfortunately, both screens (white and dark) in landscape mode are controlled by the system.
> 
> So, it is necessary to create an editor screen for the application, because the current editor screen, which is configured by the system, lacks all the elements in the vertical position, such as the note title field, Undo / Redo buttons, etc. .

I managed to find a way to disable this screen. However, there won't be any space to type. Check this image:
![IMAGE 2022-08-02 23:44:45](https://user-images.githubusercontent.com/37933889/182469890-abd10b84-891f-4346-bd4d-a0099655eafc.jpg)

**Comment by afmbsr** [comment] 2022-08-03 14:21
> I managed to find a way to disable this screen. However, there won't be any space to type. Check this image:
IMAGE 2022-08-02 23:44:45

I think the problem is caused by the keyboard that fills the screen, it hides the text input field behind it.

**Comment by afmbsr** [comment] 2022-08-08 07:34
Something strange and wonderful! . The application uses its own editor screen in landscape mode, rather than the editor screen that is configured by the system, when using a keyboard that supports floating mode in landscape mode, such as Samsung keyboard, Gboard

![Screenshot_٢٠٢٢٠٨٠٨-٠٩٥٢٣٧_Noto](https://user-images.githubusercontent.com/38974362/183364032-a80b41d5-989b-4792-a01f-e0520319aba6.png)

The next topic may bring you closer to a solution:

https://stackoverflow.com/questions/15523372/keyboard-opens-as-full-screen-in-landscape-mode

**Comment by alialbaali** [comment] 2022-08-29 20:17
What about https://github.com/alialbaali/Noto/issues/50#issuecomment-1203197949?

**Comment by alialbaali** [comment] 2023-01-03 20:11
Everything good here?

**Comment by AI-IMED** [comment] 2023-01-03 20:56
Yes👍

**Closed** 2023-01-03 20:57 UTC
Labels: bug
