### ISSUE TITLE
[Suggestion] "Save to Noto" without having to open it

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#64] opened 2022-07-25 17:41 UTC
I suggest that you make the function of the "Save to Noto" option that appears in the text selection bar is to save but without the need to open Noto (I mean save in the background), and that the text is saved in the " General" folder by default, I was using an application that includes this feature  And I loved sharing the idea with you, I see it as an easy, fast and useful way to share texts with Noto and you only need one click!.
  As for the current method, which requires choosing the save folder every time, it can be adopted with the application icon when using the “Share” option.
What's your opinion?

**Comment by alialbaali** [comment] 2022-07-26 04:43
Great suggestion.

**Comment by alialbaali** [comment] 2022-08-07 16:02
How do you think the setting should be named?

**Comment by afmbsr** [comment] 2022-08-07 16:17
I think the current name is appropriate for that

**Comment by alialbaali** [comment] 2022-08-07 16:21
You mean "Save to Noto"?

**Comment by afmbsr** [comment] 2022-08-07 16:23
Yes

**Comment by alialbaali** [comment] 2022-08-07 16:24
Don't you think it's a bit ambiguous?

**Comment by afmbsr** [comment] 2022-08-07 16:33
Well give me some time, until I find a suitable name

**Comment by afmbsr** [comment] 2022-08-07 18:20
What do you think of these two names?

Collection to Noto
QuickNoto

**Comment by alialbaali** [comment] 2022-08-07 19:35
I think Quick Note is good. I'll also add a description explaining it.

**Comment by alialbaali** [comment] 2022-08-08 14:52
How do you the user should be notified about the note being saved? I tried with showing a Toast, but then switched to showing a notification as I think it's better and more useful as you can click on it and it directs you to the note. 
![IMAGE 2022-08-08 17:37:50](https://user-images.githubusercontent.com/37933889/183443823-02364c22-c6c2-4690-a40c-6d707ff1e300.jpg)

Now there are few options on how notification can be used:
- notification can stay in the notification panel or it can have a timeout; Disappears after like 10 seconds or so.
- notification can vibrate or make a sound.

What do you think is the best configuration?

**Comment by afmbsr** [comment] 2022-08-08 15:21
I prefer showing a Toast for only 1 second, just pick up useful articles along the way and without interruption, to read and organize them later

**Comment by alialbaali** [comment] 2022-08-08 15:30
Notifications can have a timeout, just like a toast. In addition, they can be clicked to direct you to the saved note.

**Comment by alialbaali** [comment] 2022-08-08 15:35
Plus, they can be silent and do not vibrate.

**Comment by afmbsr** [comment] 2022-08-08 15:37
No please, I don't see any difference between the current method and the sharing method except that it is restricted to a specific folder

**Comment by alialbaali** [comment] 2022-08-08 15:38
Like, do you want to be other differences or what?

**Comment by afmbsr** [comment] 2022-08-08 15:48
I meant that the method you proposed to me would be a kind of duplicate of the sharing method, we only need one click and it's all over

**Comment by alialbaali** [comment] 2022-08-08 15:50
You mean notifications method? If so, with sharing you'd be directed immediately to the note with editing mode, and there are no notifications at all.

**Comment by afmbsr** [comment] 2022-08-08 16:07
I meant to click on the notification that directs me to the note, in general this method can be useful for others, it is okay to implement it :)

**Comment by alialbaali** [comment] 2022-08-08 16:09
I've made it to only show the notification for 5 seconds, and then it disappears. There are no sounds or vibrations.

**Comment by afmbsr** [comment] 2022-08-08 16:27
Don't you see that five seconds is a lot? It might make the notification a little annoying

**Comment by alialbaali** [comment] 2022-08-08 20:29
Actually, 5 seconds is the default time it takes by the system showing the notification.

**Comment by alialbaali** [comment] 2022-08-08 20:29
There will be a beta releases moving forward, so you can test it before it gets released.

**Comment by AI-IMED** [comment] 2022-08-26 10:55
Very nice work, but I think changing the phrase "Save to Noto" in the text selection options to (Quick Note) would be more clear and consistent.

**Comment by alialbaali** [comment] 2022-08-28 17:28
I agree it's more consistent, however, it might be a little ambiguous, since it doesn't mention the app. But, I'm going to rename as you suggested.

The text position depends on the text itself. Meaning, if the text contains an empty line (space) between two texts, then the first one is going to be the title, and the second one is going to be the body.

Try copying this text for example.

**Closed** 2023-01-03 19:41 UTC
Labels: enhancement
