### ISSUE TITLE
Labels don't respond to clicking

### ISSUE THREAD

**Issue by AI-IMED** [alialbaali/Noto#126] opened 2022-08-31 11:00 UTC
Steps to reproduce the problem:

- Open any folder containing labels 
- Exit the folder
- Open any other folder for about 5 seconds
- Return to the previous folder (in the first step) that contains the stickers
- Click on the labels

Result: no response

https://user-images.githubusercontent.com/38974362/187663825-fd6f8c49-8c22-48d4-bbb9-51950b52dcf8.mp4

**Comment by AI-IMED** [comment] 2022-09-12 06:49
Not fixed it.


https://user-images.githubusercontent.com/38974362/189589973-a18b89d5-0208-45ea-a591-cef41c0ce21d.mp4

**Comment by pgrilo** [comment] 2023-03-23 14:21
I have this very same problem on version 2.2.2 and at least on 2.2.1.

- Inside the Note view the Labels becomes unresponsive to touches.
- On the Folder view the Labels AND the notes Cards becomes unresponsive to touches.

I can consistently reproduce this problem by scrolling the note/folder scrollview fully to the top or to the bottom! The scroolview becomes blocked to touches only if I DRAG it slowly to the top/bottom. Scrolling to the top/bottom fast by finger flicking does not results in touch blocking.

Thank you.

**Comment by alialbaali** [comment] 2023-05-01 23:15
So, I've been trying to find out what's causing this issue for a while, and apparently, it has something to do with the bouncy scroll effect in lists. I have disabled it in the next release, and hopefully, it will fix the problem!

**Comment by pgrilo** [comment] 2023-05-24 18:21
The issue is completely fixed on my side with version 2.3.0 beta1. Thank you!

**Closed** 2023-09-08 21:13 UTC
Labels: bug
